git clone https://github.com/jaredhaight/PSAttack.git
git clone https://github.com/giMini/PowerMemory.git
git clone https://github.com/PowerShellEmpire/Empire.git
git clone https://github.com/PowerShellMafia/PowerSploit.git
git clone https://github.com/jaredhaight/PSAttackBuildTool.git
git clone https://github.com/jaredhaight/Invoke-MetasploitPayload.git
git clone https://github.com/MichaelGrafnetter/DSInternals.git
git clone https://github.com/samratashok/nishang.git
git clone https://github.com/davehull/Kansa.git
git clone https://github.com/mattifestation/PowerShellArsenal.git
git clone https://github.com/mattifestation/PSReflect.git
git clone https://github.com/FuzzySecurity/PowerShell-Suite.git
git clone https://github.com/Shellntel/OWA-Toolkit.git
git clone https://github.com/Shellntel/scripts.git
git clone https://github.com/trustedsec/unicorn.git
git clone https://github.com/Ben0xA/nps.git
git clone https://github.com/imander/DarkObserver.git
git clone https://github.com/Invoke-IR/PowerForensics.git
git clone https://github.com/Invoke-IR/PowerForensicsPortable.git
